version: '2'

services:
  
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"

  django:
    environment:
      - DJANGO_SECRET_KEY=local
      - DJANGO_DB_STRING=postgres://postgres:@postgres:5432/postgres
    image: eagerewok-django
    build:
      context: ./
      dockerfile: ./django.Dockerfile
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/eagerewok
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  node:
    image: eagerewok-node
    build:
      context: ./
      dockerfile: ./node.Dockerfile
    volumes:
      - ./:/eagerewok
    ports:
      - "4200:4200"
    working_dir: /eagerewok/angular/
    command: >
      bash -c "npm install && npm run dev"

  # documentation:
  #   restart: always
  #   build:
  #     context: ./
  #     dockerfile: ./django.Dockerfile
  #   command: "mkdocs serve"
  #   volumes:
  #     - ./:/code
  #   ports:
  #     - "8001:8001"
