version: '2'

services:
  
  django:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: django
    build:
      context: ./
      dockerfile: ./django.Dockerfile
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    # depends_on:
    #   - postgres

  node:
    restart: always
    image: node
    build:
      context: ./
      dockerfile: ./node.Dockerfile
    volumes:
      - ./:/code
    ports:
      - "4200:4200"
    working_dir: /code/angular/
    command: >
      bash -c "npm run-script dev"
    depends_on:
      - django

  # documentation:
  #   restart: always
  #   build:
  #     context: ./
  #     dockerfile: ./django.Dockerfile
  #   command: "mkdocs serve"
  #   volumes:
  #     - ./:/code
  #   ports:
  #     - "8001:8001"
